### ISSUE TITLE
CRUD, Read & Write Actions 405 Error

### ISSUE THREAD

**Issue by berglh** [floragunncom/search-guard#413]
### Environment

I'm currently testing out Search Guard for use in production and was testing the roles by incrementing the permission levels to understand the impact of each permission in Kibana for a given role and subsequent role mapping.

  - Search Guard 5.6.2-16 
  - Elasticsearch 5.6.2
  - OpenJDK Runtime Environment (build 1.8.0_151-b12)                      
  - Kibana 5.6.2
  - searchguard@5.6.2 Kibana plugin
  - 1 Data/Master Node

### Bug Description

When a user has `CRUD` access to `?kibana` index, a visualisation can be created. If I then delete that visualisation, I receive a `405 Not Allowed` error in Kibana. Refreshing the visualisation page then shows that the visualisation is actually removed.

```yaml
# Test Metrics
metrics_test_ro:
  cluster:
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    'metrics-*':
      '*':
        - SEARCH
        - READ
    '?kibana':
      '*':
        - CRUD
```

So I modified the access to `?kibana` to `READ` and `WRITE`. It turns out the exact same behaviour occured.

```yaml
...
    '?kibana':
      '*':
        - WRITE
        - READ
```

![405-delete-visualisation](https://user-images.githubusercontent.com/12455338/33416935-df0c3e54-d5ea-11e7-8e52-21406212d947.png)

So going over the documentation again, it seemed to indicate that `CRUD` was indeed like the acronym of Create, Read, Update and Delete:

#### Index-level action groups
Name | Description
---|---
CRUD | Combines the READ, WRITE and **DELETE** action groups

ref: http://floragunncom.github.io/search-guard-docs/configuration_action_groups.html

However, looking into the Action Groups, the `DELETE` method isn't included in the `CRUD` action.

#### sg_action_groups.yml
What's in the actual `sg_action_groups.yml`. The current master branch seems to indicate the same level.
```yaml
CRUD:
    - READ
    - WRITE
```
currnet master ref: https://github.com/floragunncom/search-guard/blob/master/sgconfig/sg_action_groups.yml#L70-L74

If this is the case, then both `CRUD` as well as `READ` combined with `WRITE` are apparently incorrectly enabling a user to remove a visualisation and presenting a `405` which should indicate that it wasn't deleted.

My suspicion is that just a `WRITE` operation is able to update the `?kibana` index with the new visualisation state, and that even though the operation is supposedly blocked by Search Guard, the subsequent `WRITE` is allowed through that actually overwrites the list.

I acknowledge that it would be unusual to allow a user to write a dashboard and then not enable them to delete it - even though intuitively it shouldn't as I didn't give them the privilege to do so. This maybe purely a limitation in Elasticsearch and outside the scope of what Search Guard should protect against;  feedback on this would be appreciated.

I would, however, anticipate that in `CRUD` mode, it should allow removing of the visualisation without error; my recommendation would be to change `CRUD` to *reflect it's intended purpose* by adding the `DELETE` action. If there is some valid for reason for not adding `DELETE` to `CRUD` by default, I would then begin to question the use of `CRUD` as an action name and consider changing both the name and the description in the documentation to suit.

I can of course go on my merry way by including `DELETE`, but just thought it was worth a bug report.

### Steps to reproduce
  1. Assign a user `CRUD` level action to `?kibana`
  2. Create visualisation
  3. Attempt to delete the visualisation
  4. See the 405 error appear
  5. Repeat steps 1-4 with `WRITE` and `READ` access on `?kibana`.

**Comment by floragunncom** [comment]
CRUD is exactly the same as READ and WRITE (its defined like that in default action groups). And WRITE does allow "delete". So CRUD also allows also "delete". So far so good. But a 405 should not happen (this is a status code which is not issued by Search Guard, so it seems Kibana is doing strange things). But as you said above: After refreshing the page the visualization was deleted which is expected because WRITE allows to delete. WRITE evaluates to 
<pre>
  - "indices:data/write*"
  - "indices:admin/mapping/put"
</pre>
whereas "indices:data/write/delete" is included.

So it seems that its only about the 405 here? Right?

**Comment by berglh** [comment]
Yes, I think that is a good assessment.

I haven't tested any other version than the environment I documented so I can't give you any information thus far about when exactly when the 405 Elasticsearch is returning appeared.

This does not appear with `INDICES_ALL` and the `- "indices:*"` if I remember correctly, so there must be some additional Elasticsearch action that suppresses it. When I get to work I'll experiment further.

I didn't notice the wildcard on the end of WRITE and didn't draw the association with the DELETE action name space. It makes sense, but looks a bit strange when looking at the SG action config, even though it would be redundant to add the DELETE action to CRUD.

> After refreshing the page the visualisation was deleted which is expected because WRITE allows to delete. WRITE evaluates to
>```
> - "indices:data/write*"
>  - "indices:admin/mapping/put"
>```

I'm really interpreting the definition of the actions in my testing with respect to thinking about these things from a Kibana user standpoint. I don't know if this would justify that WRITE in the Search Guard documentation be changed at all; what would have save confusion in the documentation for me would have been to define WRITE as something like:

Name | Description
-- | --
WRITE | Grants permissions to delete and write documents

Really enjoying your products so far and thanks your prompt help and explanation, the integration with our Single-Sign On has been particularly smooth.

**Comment by berglh** [comment]
Just to update on my testing process, I managed to get the `405` error to disappear by adding first adding the permission level: `- "indices:admin*"`

I then narrowed down the `405` error to being caused by the lack of the `- "indices:admin/refresh"` permission.

The last thing I haven't figured out yet is what causes the page to refresh after clicking the delete button in the visualisation screen.

If I copy all the listed permissions for `- "indices:admin"` from https://www.elastic.co/guide/en/shield/2.1/reference.html and list them all individually, the visualisation deleted but the page does not refresh. 

As soon as I added `- "indices:admin*"` it starts working, `- "indices:admin"` does not work. I can only imagine that due to the fact they stopped publishing in newer version of shield, we don't have the complete list of `- "indices:admin*"` permissions for this version of elasticsearch, and something is missing we don't know about. I even added stars to nested permissions like so and still haven't narrowed anything down.

```
        - "indices:admin/mapping*"
        - "indices:admin/cache*"
        - "indices:admin/aliases*"
        - "indices:admin/warmers*"
        - "indices:admin/validate*"
        - "indices:admin/types*"
        - "indices:admin/settings*"
        - "indices:admin/template*"
        - "indices:admin/types*"
```

**Comment by berglh** [comment]
@floragunncom So I managed to figure out it was the refresh permission level responsible for the page refresh as well; however, refresh required a trailing `*` for it to additionally refresh the page view in Kibana.

The final action group for `CRUD` that solves the `405` and visualisation screen refresh on delete is:

```yaml
    '?kibana':
      '*':
        # READ
        - "indices:data/read*"
        - "indices:admin/mappings/fields/get*"
        # WRITE | DELETE
        - "indices:data/write*"
        - "indices:admin/mapping/put"
        # 405 | Kibana Interface Refresh Fix
        - "indices:admin/refresh*"
```

**Comment by floragunncom** [comment]
Fixed with upcoming SG 17 

https://github.com/floragunncom/search-guard/commit/7fc9a74311088384302231c4989581e1c6c9f789

**Comment by berglh** [comment]
@floragunncom  

The default change in 7fc9a74 will avoid some confusion, but in my testing unless `"indices:admin/refresh*"` is included in `WRITE` or `DELETE` actions, then the 405 and refresh page issue will still appear. This is only in the case someone my choose not to use `INDICES_ALL` for access to `'?kibana`.

Did I read this fix incorrectly?
