### ISSUE TITLE
SG doesn't work after ES restart

### ISSUE THREAD

**Issue by AnisHAIL** [floragunncom/search-guard#664]
Hi SeachGuard team,
As indicate in  your anwer #568, we performed our tests (always with 1 node in the cluster) with ElasticSearch  6.6.0 and SearchGuard 6:6.6.0-24,unfortunately we have the same issue (when Elasticsearch restarts I have to run the sgadmin tool again)
How can I fix this? 

I have atteched Elastic, SearchGuard files conf with logs
The [es_sg_conf.zip](https://github.com/floragunncom/search-guard/files/3013445/es_sg_conf.zip) zicontains : 
 - elasticsearch.yml
-  sg_action_groups.yml
-  sg_config.yml
-  sg_internal_users.yml
-  sg_roles.yml
-  sg_roles_mapping.yml
- elastic.log

thank you for the feedback

**Comment by pablolescotti** [comment]
SearchGuard configuration is stored in ES indexes and sgadmin is used to load indexes from config files. So if You do not delete path.data, that should not change as index and shards become Green after restart. 

Your logs suggest that node state is RED and changes into GREEN at some point. If a shard is red, it cannot be read. Perhaps it takes a bit longer for the cluster to start. 

How do You check the cluster does not start?

**Comment by KingYL** [comment]
I have the similar problem,  every time I restarted ES, I got
`Not yet initialized (you may need to run sgadmin)`
And when I tried to run sgadmin again, sgadmin warned that the cluster's state was red and I needed to wait the cluster's state to be  yellow.
And I had tried options '--accept-red-cluster', and it failed too, logs are as follows:
`UnavailableShardsException[searchguard][0] primary shard is not active Timeout: [1m]`

To resolve the problem, I had to do the following things:
1. remove search-guard plugin and its configuration in elasticsearch.yml
2. delete search-guard's index and .kibana index
3. add search-guard plugin and its configuation
4. restart and sgadmin
5. recovery my .kibana and search-guard data

What could be the problem? Thank you for your feedback.

ES version : 6.3.2
Search-Guard version: 6.3.2-23.0

**Comment by floragunncom** [comment]
@AnisHAIL @KingYL Issue is fixed in SG 25.1 (https://docs.search-guard.com/6.x-25/changelog-searchguard-6-x-25_1)

Please upgrade to SG v25.1 (available for >= ES 6.4.3).

**Comment by floragunncom** [comment]
@KingYL Maybe you have shard allocation disabled? Run sgadmin with the `-esa` flag to enable it.

**Comment by KingYL** [comment]
@floragunncom Thanks for your reply. I tried `-esa` flag and got `Reload config on all nodes\n Reload config on all nodes`, but still I couldn't use `-cd` to initialize config with sgadmin. And I tried to restart elasticsearch service, nothing was changed.
Also, I tried to change search guard's index name in elasticsearch.yml and used `-i` with sgadmin, but still not work.

**Comment by KingYL** [comment]
@floragunncom Finally I found the reason, when I tried to remove searchguard plugin and configuration and restarted the ES, the ES was still in RED status. And it turned out that the ES was recoverying and many shards were being assigned with ES's api `_cluster/health`. There were about 10000 shards so the process was very slow. And after all the shards were assigned, ES' status was changed to YELLOW. 
And then, I tried to recovery searchguard's configuration and plugin and after waiting for a long time too, sgadmin worked and ES's status was YELLOW.
But I am still confused : when ES is assigning index shards, I cannot use any ES's http restful api to check the exact info, and would get searchguard's warning info `SearchGuard not initialized (SG11). See ....` and repeat logs `Not yet initialized (you may need to run sgadmin)` . Maybe it would be fine for developers to allow some stats info api when searchguard is not initialized.

**Comment by floragunncom** [comment]
Have a look here how to query stats info when not initialized: https://forum.search-guard.com/t/searchgurad-implementation/1540/3

**Comment by KingYL** [comment]
Thanks for the quick reply ! Oh my god, I almost forgot the admin certification used with curl.

**Comment by AnisHAIL** [comment]
Thanks for the answer, except error on my part, version 25.1 is not available for version ES 6.6.0, can you confirm this ?

**Comment by AnisHAIL** [comment]
Thanks for the answer, except error on my part, version 25.1 is not available for version ES 6.6.0(only for 6.4.3), can you confirm this ?

**Comment by floragunncom** [comment]
You need to upgrade to 6.6.2

https://repo1.maven.org/maven2/com/floragunn/search-guard-6/6.6.2-25.1/search-guard-6-6.6.2-25.1.zip
